<?php
include("header.php");
?>
<div id="content-box"> 
<div id="inside-content-box"> 
<div id="product-box">
	<img src="images/33.jpg" height="210" width="200" >
	<div id="botam">
		<h3> Photo copy <br>Price:- 10500 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/55.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Sport <br>Price:- 2400 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/41.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Bag<br>Price:- 1000 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/17.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Bittergourd<br>Price:- 1000 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/14.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Onion<br>Price:- 1000 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/21.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Face Wash<br>Price:- 1000 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/12.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Face Wash<br>Price:- 1000 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
<div id="product-box">
	<img src="images/13.jpg" height="210" width="200" >
	<div id="botam">
		<h3>Face Wash<br>Price:- 1000 <input type="submit" value="BUY" id="btn"></h3>
	</div>
</div>
</div>
</div>

<?php
include("footer.php");
?>